###
GET http://localhost:3000/api/owner/list
###
GET http://localhost:3000/api/owner/list/19.546.874-K
###
POST http://localhost:3000/api/owner/newOwner
Content-Type: application/json

{
    "rut": "19.720.997-6",
    "name": "Fabian Salanzar ",
    "mail": "f.salazars@duocuc.cl",
    "phone": 955448376,
    "housesId": [10]
}

###DEUDA
###
GET http://localhost:3000/api/owner/deuda/19.781.845-K
###
GET http://localhost:3000/api/owner/deuda/19.781.845-K/historial
###
POST http://localhost:3000/api/owner/newDeuda
Content-Type: application/json

{
    "monto": "31000",
    "fechadesde":"01/04/2022",
    "fechavenc":"05/05/2022",
    "pagado":"true",
    "fechaPago":"01/05/2022",
    "rut": "19.999.999-9"
}

###CONDOSSS
GET http://localhost:3000/api/condo/list
###
POST http://localhost:3000/api/condo/newCondo
Content-Type: application/json

{
    "condoId"     : 3,
    "name"        :"",
    "direction"   :"",
    "houseType"   : "",
    "housesAmnt"  : ,
    "expenses"    : 
}


###HOUSES
GET http://localhost:3000/api/house/list
###
GET http://localhost:3000/api/house/list/1
###
POST http://localhost:3000/api/house/newHouse
Content-Type:  application/json

{
    "houseId": 1,
    "condoId": 1,
    "price":   120000000,
    "m2":      135,
    "rooms":   3,
    "baths":   1,
    "floors":  1
}
#APLICACION
# appId: humao.rest-client
# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.24.6
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client